#  CNN NUMPY IMPLEMENTATION WITH MNIST dataset  

In [66]:
#importing required libraries
import numpy as np
import pandas as pd
from tqdm import tqdm
from keras.datasets import mnist

In [67]:
# loading dataset using 200 images

In [68]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# selecting a subset of data (200 images)
x_train = x_train[:200]
y = y_train[:200]

X = x_train.T
X = X/255

y.resize((200,1))
y = y.T


In [69]:
pd.Series(y[0]).value_counts()


1    26
9    23
7    21
4    21
3    21
0    21
2    20
6    19
8    15
5    13
dtype: int64

In [70]:
# we can see we have 9 classes here we can map into binary problem

In [71]:

# converting into binary classification
for i in range(y.shape[1]):
    if y[0][i] >4:
        y[0][i] = 1
    else:
        y[0][i] = 0

#checking value counts
pd.Series(y[0]).value_counts()

0    109
1     91
dtype: int64

# INITIALIZE FILTER FOR CONVOLUTION LAYER

In [72]:
# initialize a random convolution filter
f=np.random.uniform(size=(3,5,5)) #of 3 5x5 filers

# print first filter
f=f.T

print(f[:,:,0])


[[0.53455571 0.81708157 0.48465186 0.73870263 0.09815457]
 [0.600516   0.24551023 0.93558045 0.79008633 0.84308291]
 [0.16332105 0.56124954 0.28574953 0.59253139 0.02091304]
 [0.58499779 0.92110917 0.13519893 0.26000293 0.68798198]
 [0.2898579  0.06261737 0.19804038 0.60439871 0.10568753]]


In [73]:
X.shape,y.shape,f.shape

((28, 28, 200), (1, 200), (5, 5, 3))

In [74]:
# now for each image create 5x5 

# Smaller Patches of Images

In [75]:
# new images list
new_images=[]


for x in range(X.shape[2]):#through each image slide
    #slide in horizontal direction
    for i in range(X.shape[0]-f.shape[0]+1):
        # in vertical direction
        for j in range(X.shape[1]-f.shape[1]+1):
            new_images.append(X[:,:,x][i:i+f.shape[0],j:j+f.shape[1]])


In [76]:
new_images = np.array(new_images)

In [77]:
new_images.shape

(115200, 5, 5)

In [78]:
new_images.resize((X.shape[2],int(new_images.shape[0]/X.shape[2]),new_images.shape[1],new_images.shape[2]))

In [79]:
print(len(new_images))

200


# INITIALIZE WEIGHTS  MATRIX

In [80]:
# number of features in data set
s_row = X.shape[0] - f.shape[0] + 1
s_col = X.shape[1] - f.shape[1] + 1
num_filter = f.shape[2]

inputlayer_neurons = (s_row)*(s_col)*(num_filter)
output_neurons = 1 

# initializing weight
wo=np.random.uniform(size=(inputlayer_neurons,output_neurons))

In [81]:
wo

array([[0.70424076],
       [0.64199035],
       [0.20739187],
       ...,
       [0.13380426],
       [0.4946628 ],
       [0.57036174]])

# DEFINING ACTIVATION FUNCTION

In [82]:
def sigmoid(x):
    return 1 /( 1+np.exp(-x))

In [83]:
# derivative of Sigmoid Function
def derivatives_sigmoid(x):
    return x * (1 - x)

# DEFINING COnVOLUTION LAYER

In [84]:
filter_output=[]


for i in range(len(new_images)):
    #applying filter
    
    for k in range(f.shape[2]):
        
        #element wise multiplication
        
        for j in range(new_images.shape[1]):
            filter_output.append((new_images[i][j]*f[:,:,k]).sum())
            
            



In [85]:
filter_output = np.resize(np.array(filter_output), (len(new_images),f.shape[2],new_images.shape[1]))

In [86]:
filter_output.shape

(200, 3, 576)

# Apply activation fn

In [87]:
sigmoid_output =  sigmoid((filter_output))

In [88]:
sigmoid_output.shape

(200, 3, 576)

# Making a fully connected Layer

In [89]:
# Linear transformation part



#resizing the feature array

sigmoid_output = sigmoid_output.reshape(sigmoid_output.shape[0],sigmoid_output.shape[1]*sigmoid_output.shape[2])
sigmoid_output = sigmoid_output.T
sigmoid_output.shape

(1728, 200)

In [90]:
# Applying linear transformatiom

output_layer_input=np.dot(wo.T,sigmoid_output)




(1, 200)